version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_V}
    volumes:
      - reddit_db:/data/db
    networks:
      default:
        aliases:
          - post_db
          - comment_db
          - mongo_db
  ui:
    image: ${USERNAME}/ui:${UI_V}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  post:
    image: ${USERNAME}/post:${POST_V}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  comment:
    image: ${USERNAME}/comment:${COMMENT_V}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  reddit_db:
  prometheus_data:
